# Generated by Django 4.1 on 2023-08-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_address',
            new_name='user_city',
        ),
    ]
